export const sampleCard: App.Game[] = [
  {
    title: 'ゲームの作成について',
    lang: '',
    code: 'sample',
    codeComment: 'sample',
    description: '上の黄色いボタンからゲームを新規作成できます',
    userId: 'sample',
    index: 'sample',
    createdAt: 'sample',
    updatedAt: 'sample',
  },
  {
    title: 'ゲームの作成の詳細',
    lang: '',
    code: 'sample',
    codeComment: 'sample',
    description: 'ゲームを作るには，タイトル・コード・プログラミング言語・説明・コードのコメントを入力して，送信ボタンを押します．タイトル・コードは必須項目です．\n作成すると右のようなタイルが現れます',
    userId: 'sample',
    index: 'sample',
    createdAt: 'sample',
    updatedAt: 'sample',
  },
  {
    title: 'タイトルの例です',
    lang: '言語の例です',
    code: 'sample',
    codeComment: 'sample',
    description: '説明の例です',
    userId: 'sample',
    index: 'sample',
    createdAt: 'sample',
    updatedAt: 'sample',
  },
]
